<?php

/**
 * @file
 * Contains yandex_yml_ui.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function yandex_yml_ui_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the yandex_yml_ui module.
    case 'help.page.yandex_yml_ui':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module add UI for yandex_yml module') . '</p>';
      return $output;

    default:
  }
}
